library(dockerfiler)
dck <- Dockerfile$new("rocker/tidyverse ")
dck$RUN(r(install.packages('remotes')))
dck$RUN(r(remotes::install_github("ThinkR-open/prenomsapp")))
dck$EXPOSE(2811)
dck$COPY("Rprofile.site", "/usr/local/lib/R/etc")
dck$CMD(r(prenomsapp::run_app()))
dck$write("inst/Dockerfile")
